### ISSUE TITLE
Improve translations

### ISSUE THREAD

**Issue by berteotti** [levelkdev/swapr-dapp#1018]
**Description**
Improve translations structure and apply a key naming convention. Different scopes should be in different files for better loading.

#### Definition of done
- [ ] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**Comment by Diogomartf** [comment]
Adding namespaces to avoid collisions and have a more clear path.
