### ISSUE TITLE
Fix react fast refresh

### ISSUE THREAD

**Issue by berteotti** [levelkdev/swapr-dapp#1019]
For context, React Fast Reload makes it easy to view changes in the UI by reflecting the changes without refreshing the all page.

Our app doesn't seem to have React Fast Refresh fully operating. It should be working but our app might have some bottleneck preventing the fast refresh, like is said in this [blog page](https://javascript.plainenglish.io/react-fast-refresh-the-new-react-hot-reloader-652c6645548c). 

We have to investigate what is preventing this behaviour.

**Comment by adamazad** [comment]
CRA has [HMR](https://webpack.js.org/guides/hot-module-replacement/) by default. Elaborate on this topic.

**Comment by berteotti** [comment]
Issue is now updated with more context.
