### ISSUE TITLE
Incorrect rounded value of tokens in Swap modal

### ISSUE THREAD

**Issue by niemam29** [levelkdev/swapr-dapp#1031]
**Description**
There is some problem which makes last digit of token value rounded to zero in some cases 

#### Definition of done
- [X] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**Screenshots**
![cach2.png](https://images.zenhubusercontent.com/621e34c8aeddc379d59ee4d5/2730e059-74c8-4dcf-a123-1d83afa12b19)![cache3.png](https://images.zenhubusercontent.com/621e34c8aeddc379d59ee4d5/7d7f07f3-4c9f-4f74-8bbe-86386ac7b785)

**Comment by MilanVojnovic95** [comment]
Retested on *develop* branch and bug is still present.
