### ISSUE TITLE
Token list settings dropdown follow the scroll

### ISSUE THREAD

**Issue by MilanVojnovic95** [levelkdev/swapr-dapp#1032]
**Description**

It should probably be fixed on one place with no option to scroll along with the whole page to motivate the user to click somewhere outside that field and close settings dropdown window.

#### Definition of done
- [ ] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**How to Reproduce**
1. Go to Swap page
2. Click on 'select token'
3. Click on 'manage token lists'
4. Click on 'settings' button on one of the offered token lists
5. Try scrolling and you can see how the setting dropdown follows the scroll

https://user-images.githubusercontent.com/57331244/170718539-97619e92-685a-44df-9521-4e636d4b6372.mp4

**Comment by niemam29** [comment]
Already fixed on develop
