### ISSUE TITLE
Memory leak in Swapbox on Beta 12

### ISSUE THREAD

**Issue by adamazad** [levelkdev/swapr-dapp#1035]
**Description**

Application's JavaScript becomes slow. 

#### Definition of done
- [ ] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**How to Reproduce**
1. Go to https://swapr.site/#/swap?chainId=100
2. Select xDAI, SWPR, or any other two tokens to swap.
3. Click on the gear icon in the nav menu (probably optional)
4. Now applications generally and modals seem to lag.

**Expected behavior**

The application should run smoothly. 

**Screenshots**

**Additional context**

- Tested on Metamask on iPhone, and Chrome on macOS. 
- I suspect this could be from the USD price hook.

**Comment by sacshin** [comment]
I also tested it on .eth and .site, both on Brave and Chrome.
![visiblity change](https://user-images.githubusercontent.com/55705611/171013516-2f7e7afd-fb69-47d6-8e3b-cb42fd60bf5b.png)
![violation](https://user-images.githubusercontent.com/55705611/171013522-8fa418bb-43b3-4114-934c-57bedfd8c6aa.png)

**Comment by berteotti** [comment]
@adamazad should we close this?

**Comment by adamazad** [comment]
@berteotti yes
