### ISSUE TITLE
Looped animation on Gnosis Chain when selecting token to bridge

### ISSUE THREAD

**Issue by niemam29** [levelkdev/swapr-dapp#1075]
**Description**
The animation when pointing coursor to select token is looped. Take a look at recording please.

#### Definition of done
- [X] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**Recording**
https://images.zenhubusercontent.com/209400598/fd4a34ca-0e87-4d7a-9f92-b549c2298a9b/s.mp4

**Comment by adamazad** [comment]
@denciu

**Comment by wixzi** [comment]
@denciu I think the linked PR fixed this issue. Hence closing.
