### ISSUE TITLE
No exchange logo and name in swap button when finding route on Polygon

### ISSUE THREAD

**Issue by niemam29** [levelkdev/swapr-dapp#1077]
**Description**
No exchange logo and name in swap button when finding route on Polygon

#### Definition of done
- [X] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**How to Reproduce**
1. Go to swap page
2. Switch network to Polygon
3. Select some token in to and from fields

**Screenshots**
![cach2.png](https://images.zenhubusercontent.com/621e34c8aeddc379d59ee4d5/f882db7d-eafb-4377-89a1-c511844e88c1)

**Comment by adamazad** [comment]
@wixzi, please have a look :)
