### ISSUE TITLE
New DIY Farming Picture on the Landing Page

### ISSUE THREAD

**Issue by Mi-Lan** [levelkdev/swapr-dapp#1090]
@zamli Do you think we should update this picture it seems to reflect older desing of the DIY Farming?
![Screenshot 2022-06-14 at 20 42 13](https://user-images.githubusercontent.com/33226956/173665128-eecd6b93-f2be-444e-a889-5679188765c1.png)

**Comment by zamli** [comment]
I think we can keep it for now

**Comment by zamli** [comment]
we might do an update later on all the graphics at the same time
