### ISSUE TITLE
Eco Router is triggered when wrapping 

### ISSUE THREAD

**Issue by adamazad** [levelkdev/swapr-dapp#1115]
**Description**

<img width="565" alt="image" src="https://user-images.githubusercontent.com/1926216/174987215-b02b7470-11c2-4134-b28f-2330e51a1df2.png">

#### Definition of done
- [ ] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**How to Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Also, if it's relevant for the described byg, add information like the browser or OS.

**Comment by Diogomartf** [comment]
Fixed (caused in GPv2)
