### ISSUE TITLE
Enable 1-click auto-connect for CoinbaseWallet

### ISSUE THREAD

**Issue by sacshin** [levelkdev/swapr-dapp#1127]
Enable 1-click auto-connect for CoinbaseWallet in Swapr.
This way Swapr can be featured in the new dApp bowser of their iOS app.
Documentation: https://docs.cloud.coinbase.com/wallet-sdk/docs/ux-tips#mobile-ux-guidance

**Comment by karczuRF** [comment]
Tested by @sacshin and auto-connect works as expected.
