### ISSUE TITLE
Uncaught exception when cancelling requests

### ISSUE THREAD

**Issue by jorgedclopes** [levelkdev/swapr-dapp#1136]
A user can request the same transaction several times. If this happens while waiting for transactions to be processed some attempts may not have enough balance to be successfully processed.
In that case an exception may be raised. We are not handling these scenarios and it makes the dapp to crash.

![stack trace example](https://images.zenhubusercontent.com/6261470b0d82f7953579716f/eb2560a6-9d14-4d38-8fbe-231dcd54ef52)

**Comment by jorgedclopes** [comment]
I am not sure how to replicate this. My fault.
If no one has faced this problem I think we can close this.

**Comment by 0xVenky** [comment]
Closing this now :)
