### ISSUE TITLE
There's a discrepancy in showing a pair's swap fee between swap box and dxstats.

### ISSUE THREAD

**Issue by sacshin** [levelkdev/swapr-dapp#1177]
Swapping XDAI for SWPR, shows the fee as 0.25% in the eco-router. 
![0 25](https://user-images.githubusercontent.com/55705611/177017985-5b5ed45c-fe89-4051-8aa6-5f6fb6c9d5de.png)
But, when you go to DXstats, either on the pairs page https://dxstats.eth.limo/#/pairs, or on the SWPR token page https://dxstats.eth.limo/#/token/0x532801ed6f82fffd2dab70a19fc2d7b2772c4f4b, the pair swap fee sometimes shows as 1%, and sometimes as 0.25%,
![1](https://user-images.githubusercontent.com/55705611/177018034-11547d5d-1e79-4bb7-97e7-23974833d8f0.png)
![025](https://user-images.githubusercontent.com/55705611/177018036-d944d5d9-b28f-4f46-be92-093f4866250b.png)
 and sometimes the pair itself doesn't even appear.
![not showing](https://user-images.githubusercontent.com/55705611/177018041-915cdbe0-c9e7-44ef-94e5-97ccad199802.png)
![console](https://user-images.githubusercontent.com/55705611/177018048-e43d9f58-5f06-4f48-8dc4-a59d3eb208d4.png)

**Comment by niemam29** [comment]
Regarding inconsistency in displaying fee i think this is already fixed.
 ![cach2.png](https://images.zenhubusercontent.com/621e34c8aeddc379d59ee4d5/3d2004a8-12b1-413f-8e99-9a2923a0f9d5)
![cache3.png](https://images.zenhubusercontent.com/621e34c8aeddc379d59ee4d5/591f03a4-7eaa-40be-a434-440b084afac3)
About problems with loading pair i will take a closer look at that later and if it will still occur report another bug
