### ISSUE TITLE
Quotes expire on gnosis network (swap via CoW)

### ISSUE THREAD

**Issue by MilanVojnovic95** [levelkdev/swapr-dapp#1255]
**Description**
From time to time it happens that it is impossible to do a swap on Gnosis Chain via CoW.

#### Definition of done
- [ ] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**How to Reproduce**
1. Go to 'Swap' page
2. Select token from XDAI to USDC (for example)
3. Select 'Cow' exchange option 
4. Click on 'Wrap' button
5. Confirm wrap on Metamask
6. Click on 'Swap with CoW'
7. Click on 'Confirm Swap'
8. Click on 'Sing' (and you will get error message)

**Screenshots**
![image](https://user-images.githubusercontent.com/57331244/179197223-4dfe97f0-755a-4eef-9cba-16bc0407048f.png)

**Additional context**
This has not happened before and this was not the case earlier during testing.
Bug found on swap.site 1.0.0-beta.14.2

**Comment by jorgedclopes** [comment]
The suggested method to go around this problem is to implement some sort of TTL for the quote and request another quote when this TTL ends.

**Comment by Diogomartf** [comment]
I'm assuming TTL is this 👇

**Time to live (TTL) refers to the amount of time or “hops” that a packet is set to exist inside a network before being discarded by a router.**

**Comment by jorgedclopes** [comment]
The implementation I did, that was suggested by Adam, doesn't solve the problem. Still got

`Calling "https://protocol-xdai.gnosis.io/api/v1/orders {"method":"post","body":"{\"sellToken\":\"0xe91d153e0b41518a2ce8dd3d7944fa863463a97d\",\"buyToken\":\"0xddafbb505ad214d7b80b1f830fccc89b60fb7a83\",\"sellAmount\":\"99766104431128853\",\"buyAmount\":\"99888\",\"validTo\":1658250569,\"appData\":\"0x6c240279a61e99270495394a46ace74065b511f8d3e6899f8ce87bbaefab21de\",\"feeAmount\":\"233895568871147\",\"kind\":\"sell\",\"partiallyFillable\":false,\"signature\":\"0x20fd36e1490b971598fdab464649f4c901f136edd03844afe7078f6827efddd91e1290775378bf91063802963e3452beecb2ac24439b73bf5afb0eb31c37ca4b1b\",\"signingScheme\":\"eip712\",\"receiver\":\"0xf322fe674862649ed7f6abd747b71f27ebf88fdb\"}","headers":{"Content-Type":"application/json"}} failed with 400: {"errorType":"InsufficientFee","description":"Order does not include sufficient fee"}
`
This request was still valid for another hour.

**Comment by jorgedclopes** [comment]
I've implemented the TTL and it doesn't solve the issue. Some transactions still throw 'Insufficient fee' even though the quote is still valid.
