### ISSUE TITLE
Alternate reciver does not for Swapping

### ISSUE THREAD

**Issue by niemam29** [levelkdev/swapr-dapp#1260]
**Description**
When trying to write alternate reciver swap modal is refreshed and the reciver input is cleared

#### Definition of done
- [X] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**Recording**

https://images.zenhubusercontent.com/209400598/7887272e-4eca-4a32-9343-7c1d79457b6b/s.mp4

**Comment by MilanVojnovic95** [comment]
Tested and works ok now after @Mi-Lan fix the bug 👍
