### ISSUE TITLE
Trading xDai to USDC through Curve raises an error

### ISSUE THREAD

**Issue by daveai** [levelkdev/swapr-dapp#1272]
**Description**
When using swapr.site, attempting to do a trade from xDai to USDC raises an error message "h is undefined".

![paste (3)](https://user-images.githubusercontent.com/10086922/180646420-332d4c61-232f-4618-b848-daa85b9163f4.png)

#### Definition of done
- [ ] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**How to Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Also, if it's relevant for the described byg, add information like the browser or OS.

**Comment by niemam29** [comment]
Hey! I wasn't able to reproduce this problem. Was there any significant flow that you have follow that you followed?

**Comment by 0xVenky** [comment]
I guess this got fixed in one of the earlier releases. Beta 14.2 perhaps
