### ISSUE TITLE
stake/unstake swapr token button doesnt work

### ISSUE THREAD

**Issue by niemam29** [levelkdev/swapr-dapp#1322]
**Description**
stake/unstake swapr token button doesnt work

#### Definition of done
- [ ] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**Recording**

https://images.zenhubusercontent.com/209400598/8b8743ee-7847-4007-98a4-e6b7b40f0728/s.mp4

**Comment by sacshin** [comment]
@niemam29, there isn't any currently active single-token staking campaign.
@zamli, if we keep the menu, we should grey out the button when there are no active single-token staking campaigns, and only show it in full color when there is a live campaign. For 'unstake', even if the campaign has expired, it should stay in color if the user hasn't unstaked.
