### ISSUE TITLE
Unable to approve token on new exchanges after approving token once

### ISSUE THREAD

**Issue by berteotti** [levelkdev/swapr-dapp#1336]
**Description**
Unable to approve token on new exchanges after approving token once

#### Definition of done
- [ ] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**How to Reproduce**
1. Simulate trade using non native currency on token out
2. Click on a exchange
3. Click approve and approve token on wallet
4. Change to a new exchange
5. Approve can't be clicked again

**Expected behavior**
Approve token on one exchange, change to a new exchange and be able to approve token again.
 
**Screenshots**
![screenshot](https://user-images.githubusercontent.com/23079677/183060043-5779edff-37de-44ed-9694-1c61a2ac386e.png)

**Comment by sacshin** [comment]
Just tested in dev on Gnosis chain:
- wanted to swap WBTC for XDAI
- the eco router gave best quote on Swapr and second best CoW Protocol
- I approved WBTC, then the swap box refreshed by itself and the eco router returned the same two options
- I was allowed/able to continue the swap with either option, but chose intentionally CoW Protocol and the swap succeeded

**Comment by sacshin** [comment]
Tried again with a previously unused address and I was able to reporoduce the issue.
- the router returned two options
- I did an approval on one
- then I changed my choice of dex in the eco-router and couldn't do a new approval, I was only able to continue with a swap routing to the other exchange I already approved
- when I refresh the swap box and attempt the same trade, then I am able to do an approval and swap if I chose a different exchange
