### ISSUE TITLE
Problems with fetching arbitrum token lists on Bridge

### ISSUE THREAD

**Issue by niemam29** [levelkdev/swapr-dapp#1353]
**Description**
These 3 lists are unavailable (same case is on official Arbitrum Bridge site) :
- Arbed Uniswap List
- Arbed Gemini List
- Arbed CMC List
Fetching not reachable lists take a few minutes (3-5 min) and user cannot do anything until we got error from response.

#### Definition of done
- [ ] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**Comment by mix1o** [comment]
UPDATE: lists are working now
