### ISSUE TITLE
What happened to Sushiswap?

### ISSUE THREAD

**Issue by 0xVenky** [levelkdev/swapr-dapp#1444]
**Description**
Since the past few days, I seem to not find Sushi as one of the routes in ecoRouter. Would be good to investigate and figure why we are missing this. Is this some sort of change that Sushi did that we need to mirror?

#### Definition of done
- [ x ] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**How to Reproduce**
1. Goto swapr.eth.limo or swapr.site
2. Use WETH to USDC or WETH to SUSHI, and check if you see Sushiswap in Mainnet / Arbitrum / GNosis chain. 

**Expected behavior**
It should display Sushiswap

**Screenshots**
![image](https://user-images.githubusercontent.com/55109759/189116201-2605f5ef-6e4c-4bae-a67d-311fd9a3762a.png)

**Comment by adamazad** [comment]
Related snippet:

https://github.com/levelkdev/swapr-dapp/blob/9837f742ab67a659d76423a55e7da7c0e5c888bb/src/state/swap/hooks.ts#L242

Apparently `provider.connection.url` is missing the protocol (`https://`) and causes the next provider instance to resolve the final URL to current host + `provider.connection.url`
