### ISSUE TITLE
Swapbox initial state

### ISSUE THREAD

**Issue by 0xVenky** [levelkdev/swapr-dapp#1445]
**Description**
When the user launches swapr.eth.limo, preselect both input and output tokens in the swapbox. Each network will have a predetermined set of tokens and will be used across Simple chart and Pro mode.

![image](https://user-images.githubusercontent.com/55109759/189134579-58266114-60c3-4ae8-8024-b6be3bc53b89.png)

Mainnet - ETH and DAI
Arbitrum - ETH and USDC
Gnosis Chain - XDAI and GNO
Optimism - ETH and OP
Polygon - ETH and MATIC

#### Definition of done
- [x] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**Additional context**
This reduces the different initial states that we might need to have and getting the user what he would like to see in the first glance.

**Comment by berteotti** [comment]
Shouldn't `Gnosis Chain - ETH and GNO` be `Gnosis Chain - XDAI and GNO`?

**Comment by 0xVenky** [comment]
> Shouldn't `Gnosis Chain - ETH and GNO` be `Gnosis Chain - XDAI and GNO`?

Yea, it makes sense. Updated the description now. :)
