### ISSUE TITLE
For Swapr on Polygon - Asset shoudl be WETH"

### ISSUE THREAD

**Issue by skyminert** [levelkdev/swapr-dapp#1457]
**Description**

#### Definition of done
- [ ] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**How to Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Also, if it's relevant for the described byg, add information like the browser or OS.

**Comment by adamazad** [comment]
Superseded by #1458
