### ISSUE TITLE
Instead of  ENS it shows the address

### ISSUE THREAD

**Issue by MilanVojnovic95** [levelkdev/swapr-dapp#1468]
**Description**
On beta 15, a user who had ENS could see it instead of the address next to the network indicator, but that no longer happens.

#### Definition of done
- [ ] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**How to Reproduce**
1. Go to 'Swapr'
2. Connect wallet on Mainnet
3. See if your ENS is displayed instead of wallet address

**Expected behavior**
If user owns ENS it should be displayed.

**Screenshots**
BETA.15
![image](https://user-images.githubusercontent.com/57331244/189849019-0459314f-8e38-4d84-b480-85ea19725cb6.png)

BETA.16
![image](https://user-images.githubusercontent.com/57331244/189849169-6c1d2468-6b30-48dd-aaed-f89ed6b05f39.png)

**Comment by niemam29** [comment]
For me it's working - but i have only tested it on Rinkeby soo it may be an issue only for mainet

**Comment by 0xVenky** [comment]
Hey @MilanVojnovic95 can you retest this one moretime? Seem to work for me in mainnet

**Comment by 0xVenky** [comment]
Closing this now, Milan confirmed he could see.
