### ISSUE TITLE
Add BSC network

### ISSUE THREAD

**Issue by jorgedclopes** [levelkdev/swapr-dapp#1471]
### Adding BSC to Swapr includes:

SDK:

- add basic config (chainId, native currency, core tokens, etc.)
- investigate which DEXes can be ecoRouted and include them. Probably use pancakeSwap.

FE:

- enable adding/switching network to BSC
- disable Swapr specific features when connected to BSC (disable Liquidity, Rewards)

Bridge:

- enable BSC support on Socket
- add bridgable tokens for BSC

**Comment by jorgedclopes** [comment]
The implementation is mostly done. The only outstanding thing to do is

- Release the SDK
- Fix the package import
- Possibly fix any minor issue that arose during the last couple of weeks.

Best of luck

**Comment by MuratKok1** [comment]
Kontrol paneli
