### ISSUE TITLE
Create campaign button on landing page should be blocked when on Polygon or Optimism

### ISSUE THREAD

**Issue by niemam29** [levelkdev/swapr-dapp#1477]
**Description**
Create campaign button on landing page should be blocked when on Polygon or Optimism (those nets got no campaign contracts deployed yet)

#### Definition of done
- [ ] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**Recording**

https://images.zenhubusercontent.com/209400598/ad1321a1-a3ab-4a6d-bef6-29eb3ce9c6d9/s.mp4

**Comment by 0xVenky** [comment]
Good catch! We might fix this by adding a default page on unsupported network. :)
