### ISSUE TITLE
Limit Order - Summary once user places Limit Order

### ISSUE THREAD

**Issue by 0xVenky** [levelkdev/swapr-dapp#1607]
It would be nice to give the user a summary of the limit order. 1inch gives a nice overview before the user is taken to the wallet.

@zamli wanna design something up?

![image](https://user-images.githubusercontent.com/55109759/205692505-59fb3add-b2c6-42f1-a32b-ade21b8ee061.png)

**Comment by zamli** [comment]
Here is the design
![image](https://user-images.githubusercontent.com/25611956/206213549-28dc4fb5-badd-4c06-858f-ac4800489f45.png)

https://www.figma.com/file/sh1SahVJbRgCk2kIrxNgyG/Swapr-1.5?node-id=2102%3A19051&t=Dniy7UlAU28DvQlD-1
