### ISSUE TITLE
Landing page updates

### ISSUE THREAD

**Issue by 0xVenky** [levelkdev/swapr-dapp#1609]
1. Include BNB chain and Optimism here: 

![image](https://user-images.githubusercontent.com/55109759/205694305-76aefbb8-222a-47fa-8b49-66e1d611924b.png)

2. Update roadmap to reflect the latest status.
3. Use the latest medium articles for ecoRouter, SWPR token and full mEV protection article. If Advanced trading view has gone out already, replace SWPR token with advanced trading view.

**Comment by Mi-Lan** [comment]
Also would be good to update swapr stats 
![Screenshot 2022-12-07 at 13 04 44](https://user-images.githubusercontent.com/33226956/206175021-180f354f-e37c-434d-a3f7-86ff804a8161.png)
