### ISSUE TITLE
Wrongly displayed network in Bridge Box

### ISSUE THREAD

**Issue by MilanVojnovic95** [levelkdev/swapr-dapp#1612]
**Description**

#### Definition of done
- [ ] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**How to Reproduce**
1. Go to 'Swapr'
2. Connect to some Network
3. Go to 'Bridge' page

**Expected behavior**
It always shows the message 'Connect to Ethereum' and shows Ethereum as the selected network even though the situation is different and the user is already connected to the desired network.

**Screenshots**
![image](https://user-images.githubusercontent.com/57331244/205915478-46d3843e-e55a-428a-863b-0ef0c5153986.png)

![image](https://user-images.githubusercontent.com/57331244/205915725-0d0ad909-2f05-46cf-b9ff-ed1c058efd35.png)

**Additional context**
Also, if it's relevant for the described byg, add information like the browser or OS.

**Comment by 0xVenky** [comment]
I think this works correctly. So, the user could be in any chain and he is trying to bridge some assets from ETH to Arb1 and when he is ready to bridge, he would click on "Connect to Ethereum" that will trigger a switch network. 

Lmk if this makes sense and close this if you agree. :)

**Comment by 0xVenky** [comment]
Closing this one :)
