### ISSUE TITLE
Zapping from pair crashes swapr

### ISSUE THREAD

**Issue by zamli** [levelkdev/swapr-dapp#1622]
https://images.zenhubusercontent.com/209400598/43ff0a87-3f86-4df5-ac39-d42a5e60fb51/chrome_4ordruasjc.mp4

Here is how to reproduce the bug.
1. choose dai
2. Choose the pair Cow/eth
3. Press the invert button.
4. On cow/eth choose type 1
5. dApp crashes

**Comment by karczuRF** [comment]
Fixed with [9acae00](https://github.com/levelkdev/swapr-dapp/pull/1596/commits/9acae00618d0f0b212dce24a1a473940bd053662)
