### ISSUE TITLE
Action the start of Liq Mining for that pair

### ISSUE THREAD

**Issue by skyminert** [levelkdev/swapr-dapp#227]
For me, if you are going to show the "Create Liq. Mining" button when you are on a chosen pair, it should action the start of Liq Mining for that pair.  Not bring you to the General Liq Mining page.  

![image](https://user-images.githubusercontent.com/57817726/114642635-1adbd800-9c89-11eb-911a-b69b5c23d103.png)

**Comment by 0xVenky** [comment]
Need your views here @zamli

**Comment by zamli** [comment]
I dont think we can pre define the settings for the specific pair in the creation. Maybe we can do that for later versions.

Are you also suggesting to make the "create liq mining" button the action? @skyminert

**Comment by skyminert** [comment]
If after navigating to a Pair, there is a button that says "Create Liq. Mining" i would think it would be for that pair.  Which is also why i was confused by "Create Pair".  Those are both right next to the pair name.  

If those are just general buttons related to Pools, maybe they could be above or outside the Pair Specific box.  

Like, at any time, you can "Create Pair" or "Create Rewards Pool".
These buttons should likely look the same as they are equals, no?

**Comment by 0xVenky** [comment]
Hey, closing this as it doesnt feel relevant anymore because of the new designs. If, in case this is still needed, feel free to reopen the ticket.  :)
