### ISSUE TITLE
Confusing Buttons

### ISSUE THREAD

**Issue by skyminert** [levelkdev/swapr-dapp#228]
If you are on a Pair that exists.
Should you be highlighting the "Create Pair" button?

Also the "Create Liq Mining" button looks grayed out.  

Most people probably want to ADD or REMOVE liquidity, right?

![image](https://user-images.githubusercontent.com/57817726/114642853-70b08000-9c89-11eb-8336-0bbc94ac0c60.png)

**Comment by zamli** [comment]
Looks like this is how i designed it
![image](https://user-images.githubusercontent.com/25611956/114858484-ce5bde00-9de9-11eb-8325-e2700f4fe908.png)

**Comment by zamli** [comment]
I will need to make an issue to fix the color of the "grey" buttons and to remove the action to "create pair" when you are inside of a specific pair

**Comment by skyminert** [comment]
Maybe not remove them.  They could always be accessible as tooling but not part of the specific pair.  

---------
If those are just general buttons related to Pools, maybe they could be above or outside the Pair Specific box.

Like, at any time, you can "Create Pair" or "Create Rewards Pool".
These buttons should likely look the same as they are equals, no?

**Comment by 0xVenky** [comment]
Closing this, because of designs that aree updated and a new Liquidity page / DIY farming is coming up soon.
