### ISSUE TITLE
Suggest additional information for "Add Liquidity" page.

### ISSUE THREAD

**Issue by KeenanLukeOM** [levelkdev/swapr-dapp#240]
_Note: These are thoughts, and could be debated in their effectiveness. This isn’t a necessity and doesn’t negatively affect my experience, but it would definitely be supplemental if I am considering where and how much to LP._

With the introduction of farming some additional information could help with the LP flow.

Suggest implementing: 

- "Has active/upcoming farming campaign" stat, that can either be "yes" or "no".

- "Estimated APY" stat based off DXstats information. If we wanted to be tricky, we could account for the estimated APY of the current highest yielding farm as well as fees, denoted as "Optimized APY", "Fees + Farming Estimated APY" or something similar.

![image](https://user-images.githubusercontent.com/76129769/114781232-46b09980-9d2d-11eb-9009-e777a3a0a0ff.png)

_Pictured: Where these would fit. Below/within the current information._

Another relatively simple solution to this would be introducing "Reward pools" as something viewable below the liquidity provision page. This prevents a user from needing to open multiple tabs of Swapr when possible, or needing to go back and forth between the pairs page and the liquidity provision page when making an LP decision.

![image](https://user-images.githubusercontent.com/76129769/114781524-a27b2280-9d2d-11eb-891b-fd6980173732.png)

_Pictured: Adding this page below the "Add liquidity" window would likely be an improvement._

**Comment by 0xVenky** [comment]
Not relevant anymore.
