### ISSUE TITLE
WalletConnect broken on non ethereum

### ISSUE THREAD

**Issue by PeterTheOne** [levelkdev/swapr-dapp#277]
WalletConnect is not configured for the correct network on non ethereum chains. It still request Ethereum as a network and even if that is ignored by the wallet it then thinks it is connect to Ethereum even when the wallet sends a chainChanged event to the dapp.

Try with [Minerva](https://minerva.digital/) or https://test.walletconnect.org/ .

**Comment by tze42** [comment]
There are 2 possible solutions for this problem in the case of Swapr at https://swapr-eth-link.ipns.dweb.link/
1) Use separate WalletConnect options like it is done for Honeyswap https://app.honeyswap.org
2) Use a custom network selection as it is done by Tornado Cash https://tornadocash.eth.link/ (very well done) or Superfluid https://app.superfluid.finance

**Comment by sacshin** [comment]
@0xVenky 
When disconnecting a WalletConnect connection on the dapp side, the wallet isn’t getting a message. 
It seems like the disconnect only works fully if a person disconnects from their wallet.
While connected to the Ethereum network, once you click on "Disconnect" in Swapr and then change network to Gnosis Chain, it autoconnects back to Ethereum. It should not autoconnect, it should ask which wallet to use.

**Comment by 0xVenky** [comment]
Fixed as part of one of the earlier releases.
