### ISSUE TITLE
Swapr UI Showing Half of TVL

### ISSUE THREAD

**Issue by jpkcambridge** [levelkdev/swapr-dapp#409]
<img width="684" alt="Screen Shot 2021-09-30 at 11 05 48 AM" src="https://user-images.githubusercontent.com/874683/135481387-654458c7-6c50-4a18-ad52-8d7794f9f0a6.png">
<img width="329" alt="Screen Shot 2021-09-30 at 11 05 56 AM" src="https://user-images.githubusercontent.com/874683/135481410-8478c5b0-3b3e-442a-9cb4-a6a180adc823.png">

These screenshots were take right after start of Epoch 2

**Comment by 0xVenky** [comment]
Fixed as part of one of the earlier versions of dxstats
