### ISSUE TITLE
WalletConnect missing 'disconnect'.

### ISSUE THREAD

**Issue by sacshin** [levelkdev/swapr-dapp#504]
Some wallets like Minerva wallet are using WalletConnect exclusively when connecting to dApps, so they need a fully working WalletConnect to integrate Swapr. We have a working chain selector, but it's missing "Disconnect" on the DApp side.

**Comment by 0xVenky** [comment]
Implementation: https://gyazo.com/85a9a39246b97d2f2a61ff3e8537f566

On a connected wallet, a new "Disconnect wallet" has to be added. When the user clicks on this button, the dapp should go to disconnected state and disconnect wallet from the wallet.

Where to place: Click Network dropdown and then choose Change wallet, under wallets "Authereum" for now, add this new button.

**Comment by zamli** [comment]
Design in case we need it
![image.png](https://images.zenhubusercontent.com/61238acceb6eacff74da8a43/94e0fd49-0371-40fe-8aa9-c0c5cea29c9a)
https://www.figma.com/file/L8tamoiv3mTCRaypHLk1us/DXswap?node-id=6232%3A37294

**Comment by 0xVenky** [comment]
Closing this as the change is merged in devlop with an option to disconnect wallet.

**Comment by 0xVenky** [comment]
Closing this as the change is merged in devlop with an option to disconnect wallet.

**Comment by 0xVenky** [comment]
Closing this as the change is merged in devlop with an option to disconnect wallet.
