### ISSUE TITLE
Wrong validation in "Slippage tolerance" field in settings

### ISSUE THREAD

**Issue by kingalg** [levelkdev/swapr-dapp#523]
Path: Settings -> Slippage tolerance -> last field

![Screenshot 2021-12-17 at 12.28.53.png](https://images.zenhubusercontent.com/61b8ae8c4021b5ba7f93dbf2/82316220-dd59-407a-b8b1-2309a5ee9958)

Validation seams to be broken - there is that warning sign sometimes (also it's not clarified what does it means exactly - it still let the user to use this percentage even with a warning). 

The user can also choose negative number (he definitely shouldn't be), however if he does and try to use "swap" (by choosing two and entering amount) he will crash the app. We should block possibility of entering some amounts. 

![Screenshot 2021-12-17 at 12.46.35.png](https://images.zenhubusercontent.com/61b8ae8c4021b5ba7f93dbf2/7f6cf9fd-94b0-4573-ab17-a0714685a3e4)
![Screenshot 2021-12-17 at 12.49.28.png](https://images.zenhubusercontent.com/61b8ae8c4021b5ba7f93dbf2/a99d1528-0a9b-4290-b2d4-18563eac87e7)

The last small thing about this area is how it looks like - last field should be visually different from the others as it let the user to do a different action (write something, not only choose).

**Comment by 0xVenky** [comment]
We can close this one right? @kingalg  Remember this was fixed as part of a differnt issue

**Comment by MilanVojnovic95** [comment]
@0xVenky 
Tested and bugs from this issue are fixed so I will close this issue.
