### ISSUE TITLE
users requested info in the DIY farms to clarify some functions

### ISSUE THREAD

**Issue by sacshin** [levelkdev/swapr-dapp#547]
We've received feedback form users/partner projects.
Some of the functions are self-explanatory, but others can do with an info bubble with meta text on hover over to clarify purpose. For example the time lock function to explain it's about "locking LP stake for the duration of the campaign", not anything else.  
Possibly also adding a note for the multi-reward farm button, so people don't try to click it many times or wonder why it's inactive.

**Comment by MilanVojnovic95** [comment]
@0xVenky 
Tested and not all tasks from this issue are implemented, it might not be bad to include in as part of [#942](https://github.com/levelkdev/swapr-dapp/pull/942)?

**Comment by 0xVenky** [comment]
Lets close this for now. We need to look at the dapp as a whole and see minor areas of improvement. DIY farming and campaign creation including. :)
