### ISSUE TITLE
Integrate COWSwap

### ISSUE THREAD

**Issue by 0xVenky** [levelkdev/swapr-dapp#578]

**Comment by MilanVojnovic95** [comment]
This issue is connected to #1009[](https://github.com/levelkdev/swapr-dapp/pull/1009) It seems to me.
@0xVenky @jorgedclopes 
Please confirm to me if so that I can change the state of this issue in ''Review''.

**Comment by adamazad** [comment]
@MilanVojnovic95 can we track #981 instead? It has more context. :)

**Comment by MilanVojnovic95** [comment]
@adamazad  Sure, so I will change the state of issue to in 'Review'.
