### ISSUE TITLE
When collect fails, we need to provide user an option to retry

### ISSUE THREAD

**Issue by 0xVenky** [levelkdev/swapr-dapp#587]
![image](https://user-images.githubusercontent.com/55109759/151446238-052ae1a3-313a-40b5-b887-17c8d9c2251c.png)

When collect fails in Mainnet, we need to give the user an option to retry the failed transaction. Right now, the UI is stuck at Pending and the user cannot perform any action.

**Comment by denciu** [comment]
Tx hash https://etherscan.io/tx/0x1fd5a202427e6e29af4c70370d582c6736eced416b82e2497cbccb3cdf3f42de

**Comment by 0xVenky** [comment]
Checked with @karczuRF this can be closed now
