### ISSUE TITLE
New SWAPBOX design

### ISSUE THREAD

**Issue by Mi-Lan** [levelkdev/swapr-dapp#596]
- There is a new design for swapbox on figma which will go along the landing page changes
![Screenshot 2022-01-28 at 15 00 06](https://user-images.githubusercontent.com/33226956/151559678-f19414ea-4def-47a0-8d50-313e67c9adfb.png)
- figma link https://www.figma.com/file/L8tamoiv3mTCRaypHLk1us/DXswap?node-id=4539%3A25236

**Comment by zamli** [comment]
There will be an update on the new swap box. Wait until i'll update this issue

**Comment by 0xVenky** [comment]
Closing this as its not relevant anymore..
