### ISSUE TITLE
Sort imports and allow absolute paths imports

### ISSUE THREAD

**Issue by berteotti** [levelkdev/swapr-dapp#628]
I would be nice to have a prettier plugin has this one [prettier-plugin-sort-imports](https://www.npmjs.com/package/@trivago/prettier-plugin-sort-imports), it would be easier to find, read and add file imports.

Also, it would be nice to allow absolute paths, so it's easier to import 1st level files.
Right now we import like this:
```ts
import { TYPE } from '../../../../../../theme'
```
It will look like this:
```ts
import { TYPE } from 'theme'
```

**Comment by Diogomartf** [comment]
Yes. 

We should also sort the imports so it's easier to grasp what's imported:

Something like (top -> bottom)
1. External libs
2. hooks
3. components

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/5664434/164484324-55f11276-edaf-45eb-9600-af46122d9cf1.png">
