### ISSUE TITLE
Settings buttons

### ISSUE THREAD

**Issue by 0xVenky** [levelkdev/swapr-dapp#642]
This issue is around the buttons that we have here in the design:
![image](https://user-images.githubusercontent.com/55109759/156770217-49d33549-28f6-4bdf-a847-69ddada894ba.png)

Icon 1 - tells the user whats the slippage % he has set 
Icon 2 - tells the user if Multihop is enabled or disabled
Icon 3 - if the user has chosen Swap and Send or Alternate Receiver
Icon 4 - if the user has MEV protection on. Usually, this is ON if the ecoRouter is through COWSwap.

Icons 1 and 2 are interactive and clicking on them should just open the settings dialog.
Icons 3 and 4 are not interactive but the states will change based on how the user is performing the swap.

We need to add tooltips to each of these icons.
Icon 1 - Slippage %
Icon 2 - Multihop enabled (if Green) and Multihop disabled (if Grey)
Icon 3 - Alternate Receiver
Icon 4 - MEV Protection (coming soon)

**Comment by zamli** [comment]
We can "disable" the mev protection button until we launch MEV protected swaps. There is some logic that includes when we turn it on later. We should have a hover description of them all too.

Everything else sounds like what was planned.
