### ISSUE TITLE
Swap button

### ISSUE THREAD

**Issue by 0xVenky** [levelkdev/swapr-dapp#645]
- [ ] Change the text to include which dex is used to route the trade
- [ ] The button should be a gradient with one color being the Swapr blue and the other being a primary color for the exchange being traded on.
- [ ] Include the routed dex's icon

Design: https://www.figma.com/file/L8tamoiv3mTCRaypHLk1us/DXswap?node-id=6807%3A106903

**Comment by MilanVojnovic95** [comment]
The button should be a gradient with one color being the Swapr blue and the other being a primary color for the exchange being traded on.
Suggestion:
The Uniswap color is not blue as for Swapr
![image](https://user-images.githubusercontent.com/57331244/157439789-1acc16e5-ec30-4a80-87bf-cf21cfd99d20.png)
I think we should use rgb(232, 0, 111) as on Uniswap
![image](https://user-images.githubusercontent.com/57331244/157440073-958377d5-1071-4cab-a7a4-e213aeede511.png)

**Comment by 0xVenky** [comment]
Hey @MilanVojnovic95 until we have figured out the right colors for all exchanges, we discussed to just create a map that defaults to the native blue for now. Before we actually make a release, we would need to update the right values.
