### ISSUE TITLE
DXswap Light mode theme

### ISSUE THREAD

**Issue by zamli** [levelkdev/swapr-dapp#67]
Follow the guidelines of figma + the brand portal

![image](https://user-images.githubusercontent.com/25611956/98233394-47aff480-1f5f-11eb-899e-51211c088fac.png)

https://www.figma.com/file/L8tamoiv3mTCRaypHLk1us/DXswap?node-id=101%3A7308
https://zeroheight.com/966ad5485/p/46c33a-dxswap-theme/b/9692cf

**Comment by 0xVenky** [comment]
Closing and cleaning up the backlog.
