### ISSUE TITLE
Switch between Metamask and Coinbase wallets problem

### ISSUE THREAD

**Issue by karczuRF** [levelkdev/swapr-dapp#683]
In general wallet switching works fine, but in some cases doesn't. Didn't check how does it looks like with another wallets.

Steps to reproduce problem:
1. Launch app and be sure that no wallet is connected yet.
2. Connect with Coinbase wallet.
3. If connected succesfully with Coinbase, try to change to Metamask
4. When Metamask popup will show asking for account connection select **Cancel**.
At that moment it's shown that Metamask is connected, but in fact it's not and address is still the one from Coinbase wallet.

![image](https://user-images.githubusercontent.com/88723742/154741188-db2e9966-cd0c-4fb6-9c98-60310c1f0edd.png)

5. Try to connect Metamask or Coinbase. In both cases wallet doesn't response and "Initializing..." info is shown infinitely. Coinbase wallet address still can be seen.

![image](https://user-images.githubusercontent.com/88723742/154742226-8748878f-b547-439a-b196-97cb05270275.png)

**Comment by Bleujj1** [comment]
You will have to synchronize your wallet with bech 13 and then you debug it

**Comment by karczuRF** [comment]
@kingalg I would be grateful if you could check this case as well with different wallets ;)

**Comment by Bleujj1** [comment]
@karczuRF. You can use ellipal bech13 to fix the issue

**Comment by karczuRF** [comment]
Related issues:
https://github.com/NoahZinsmeister/web3-react/issues/300
https://github.com/NoahZinsmeister/web3-react/issues/163#issuecomment-1010210571

**Comment by MilanVojnovic95** [comment]
This bug is fixed in #1330
