### ISSUE TITLE
Uneven margin on loader in balance widgets   

### ISSUE THREAD

**Issue by adamazad** [levelkdev/swapr-dapp#701]
![image](https://user-images.githubusercontent.com/1926216/155829080-c097de0f-6067-45f4-954d-c6fed3ca69d7.png)

**Comment by adamazad** [comment]
<img width="986" alt="image" src="https://user-images.githubusercontent.com/1926216/182872298-7ab9a342-fb4b-4279-a58d-8f663eb97363.png">

Doesn't happen develop.

**Comment by MilanVojnovic95** [comment]
Retested and I can confirm that bug is no longer present on the develop branch.
