### ISSUE TITLE
Invalid label when wrapping and unwrapping ethereum

### ISSUE THREAD

**Issue by niemam29** [levelkdev/swapr-dapp#720]
#### Issue description

When user select ETH in "from" section and WETH in "to " section label on the wrap button and the amount in "from" section is null or 0 the label is incorrect

#### Steps to reproduce the issue

1.  Open SWAP page of SWAPR
2.  Select ETH in "from" section
3.  Select WETH in "to" section
4.  Make sure that in "from" section there is no value or type in 0.0

#### What's the expected result?

Label on "Wrap" button is making user know that he should enter value in order to commit transaction. For example "Enter ETH amount"

#### What's the actual result?

- Label on "Wrap" button is "Insufficient ETH balance"

#### Additional details / screenshot

Second screenshot is from uniswap

![cache.png](https://images.zenhubusercontent.com/621e34c8aeddc379d59ee4d5/c6e7c46a-518d-4d0d-981c-db2b12c88844)

**Comment by niemam29** [comment]
@berteotti 
Hey, founded that there are some missing spaces when insufficient balance
![cache.png](https://images.zenhubusercontent.com/621e34c8aeddc379d59ee4d5/dbb93a71-e84c-4fc6-9078-9f82075d68b0)

**Comment by berteotti** [comment]
@niemam29 It's now fixed!

**Comment by niemam29** [comment]
For me it now looks good
