### ISSUE TITLE
Enable DIY dual rewards

### ISSUE THREAD

**Issue by 0xVenky** [levelkdev/swapr-dapp#748]
Right now, the dual rewards campaign is disabled in the frontend, but the contracts has been working and used in all the chains. Would be good to get this enabled, tested and released soon.

**Comment by Mi-Lan** [comment]
- The new designs https://www.figma.com/file/L8tamoiv3mTCRaypHLk1us/DXswap?node-id=7275%3A31644
- live figma version https://www.figma.com/proto/L8tamoiv3mTCRaypHLk1us/DXswap?page-id=7275%3A31644&node-id=7275%3A32725&viewport=419%2C48%2C1&scaling=min-zoom&starting-point-node-id=7308%3A226881
