### ISSUE TITLE
Implement error handing for the Landing Page components

### ISSUE THREAD

**Issue by Mi-Lan** [levelkdev/swapr-dapp#795]
**Description**
When graph is down app crashes in Stats.js component I think we should look into implementing error catchers for all non essential parts in LandingPageComponents folder
**How to Reproduce**
I will give example for just Stats.js folder but should be checked for all LandingPageComponents
1. Go to src/components/LandingPageComponents/Stats.js
2. fuck up one of the apiUrlList(also they should be imported from the clients.js folder) url-s by for example on xdai removing one letter
3. Refresh the page

**Screenshots**
This is error  Im seeing  even on page refresh
![Screenshot 2022-03-21 at 14 16 22](https://user-images.githubusercontent.com/33226956/159269983-7ec319bd-25e6-45a4-ae06-1d2a7847f59d.png)
![Screenshot 2022-03-21 at 14 24 43](https://user-images.githubusercontent.com/33226956/159270072-1f198a9b-678c-455d-83f1-eceb76f937ce.png)

**Comment by Diogomartf** [comment]
I'm wondering if we should show feedback to users like "failed to fetch from some APIs" or if should be hidden as it might not be relevant.

**Comment by Diogomartf** [comment]
I'm wondering if we should give some feedback when it fails to update the data.

I was thinking of something like this: "not updated".

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/5664434/162731397-5a4aa6ef-3938-429c-a392-7166add75ef7.png">
