### ISSUE TITLE
Balance when not connected 

### ISSUE THREAD

**Issue by zamli** [levelkdev/swapr-dapp#823]
![image](https://user-images.githubusercontent.com/25611956/160301083-ccaf9d54-332b-47f5-a96a-a1bba075c6a0.png)
Hide balances when not connected

**Comment by 0xVenky** [comment]
Guess this one is fixed in one of the earlier versions. 🤔  closing this for now, our dev version of swapr instance works ok. If this is still a problem, lets reopen this one.
