### ISSUE TITLE
Patch 404 errors

### ISSUE THREAD

**Issue by adamazad** [levelkdev/swapr-dapp#829]
- Remove Opyn token list
- Fix path to translation locale
- Find a better token list that has all updated information. If it's Swapr token list, patch them in the respective repo.

Ref:
<img width="1338" alt="image" src="https://user-images.githubusercontent.com/1926216/160433718-214c9a2e-0a27-41d6-a106-38c09700ce4e.png">

**Comment by jorgedclopes** [comment]
I am doing a quick fix on this.
The path was changed on the 3rd party side.
We should get some monitoring tool to highlight these 400/500 http errors from within Swapr to relieve manual checking.

**Comment by jorgedclopes** [comment]
We are failing to replicate the locale issue at this point.
Regarding the token information... It is not quick to solve this one.

**Comment by MilanVojnovic95** [comment]
This bug was fixed in #925 and merged.
