### ISSUE TITLE
Add cogwheel to Liquidity manager dialog

### ISSUE THREAD

**Issue by 0xVenky** [levelkdev/swapr-dapp#848]
Currently, in the Add Liquidity page, we have a question mark button that shows tooltip upon hovering over.
![image](https://user-images.githubusercontent.com/55109759/161617978-19292987-a688-498f-8755-58bbf4cc2f40.png)

Replace the question mark with a cogwheel.
Upon clicking on the cogwheel, open settings that are relevant to adding liquidity. We can use the same settings as what Sushiswap displays :), also given below a pic from their dapp.

![image](https://user-images.githubusercontent.com/55109759/161618485-e4dea851-3c38-466e-8b39-da5d032b2069.png)

![image](https://user-images.githubusercontent.com/55109759/161619131-6aa2791f-4649-4b70-896e-7e109e9a116b.png)

**Comment by Diogomartf** [comment]
Does interface settings make sense here?

**Comment by zamli** [comment]
![image](https://user-images.githubusercontent.com/25611956/161968153-215412f2-5c3a-47e3-aa81-5fa9a88cd93f.png)
This is how the settings pops up here.
The slippage here and inside of our default settings is the same. Changes made on both effects both places
https://www.figma.com/file/L8tamoiv3mTCRaypHLk1us/DXswap?node-id=8130%3A37981

**Comment by Diogomartf** [comment]
After talking with @zamli, we settled on th
