### ISSUE TITLE
Add Polygon support

### ISSUE THREAD

**Issue by denciu** [levelkdev/swapr-dapp#853]
Adding Polygon to Swapr includes:

SDK:
 - [x] add basic config (chainId, Matic native currency, core tokens on Polygon like WETH, USDC, USDT, etc.)
 - [x] enable Sushiswap on Polygon
 - [x] add Quickswap to `UniswapV2RoutablePlatforms`

FE:
 - [x] enable adding/switching network to Polygon
 - [x] disable Swapr specific features when connected to Polygon (disable `Liquidity`, `Rewards`)

Bridge:
 - [ ] enable Polygon support on Socket
 - [ ] add bridgable tokens for Polygon

~Due to upcoming major changes in SDK, #616 is used as a base branch (both on SDK and FE)~.

**Comment by adamazad** [comment]
#879 updates the SDK version. `develop` should be used as the base for this.
