### ISSUE TITLE
ecoBridge - The loading indicator is not following the Swapr design

### ISSUE THREAD

**Issue by 0xVenky** [levelkdev/swapr-dapp#870]
**Description**
When user selects a bridge, the loading indicator looks to miss the Swapr theme.

#### Definition of done
- [x] Description is created (Task creator)
- [x] Code is complete (Developer)
- [x] Scope of test and what was done section is defined in task (Developer)
- [x] Review passed (Code reviewer)
- [x] Verified manually (QA)
- [x] Test cases created/updated if necessary (QA)
- [x] Change successfully merged
- [ ] Release notes added if needed

**How to Reproduce**
https://gyazo.com/1437c0451e3d6e917a10f1725669cda9 

**Expected behavior**
Redesign and reimplement the loading indicator

**Test**
- check color of spinner

**Comment by niemam29** [comment]
Lgtm!

**Comment by mix1o** [comment]
Closed by #874
