### ISSUE TITLE
ecoBridge - Placeholder content on an empty history page

### ISSUE THREAD

**Issue by 0xVenky** [levelkdev/swapr-dapp#871]
**Description**
When there is no history, the history tab has no content and looks a bit broken. Would be nice to add some placeholder content on a blank tab.

![image](https://user-images.githubusercontent.com/55109759/162693398-6230df14-bb3a-4e6d-ae95-47f60264af70.png)

#### Definition of done
- [x] Description is created (Task creator)
- [x] Code is complete (Developer)
- [x] Scope of test and what was done section is defined in task (Developer)
- [x] Review passed (Code reviewer)
- [x] Verified manually (QA)
- [x] Test cases created/updated if necessary (QA)
- [x] Change successfully merged
- [x] Release notes added if needed

**Comment by mix1o** [comment]
Now there is only a text. Later we can improve design  
![image](https://user-images.githubusercontent.com/46563377/165706355-f9f0176e-aade-4578-a08c-c163181e5f5e.png)
