### ISSUE TITLE
Problem with loading Liquidity value when choosed specific position in DXstats

### ISSUE THREAD

**Issue by niemam29** [levelkdev/swapr-dapp#877]
**Description**
When user go to accounts and click on some wallet, click on some wallet address, and then switch from all positions to specific one the liquidity chart is loading infinitely.

#### Definition of done
- [x] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**Screenshots**
![cach2.png](https://images.zenhubusercontent.com/621e34c8aeddc379d59ee4d5/092ffc53-6dfb-48f8-bf9c-bd0a177dcfd7)

**Comment by 0xVenky** [comment]
Hey, going to close this one here. Can you retest once in https://deploy-preview-55--swapr-analytics.netlify.app/#/home and then if it still occurs, create a bug in https://github.com/SwaprDAO/swapr-info
