### ISSUE TITLE
Liquidity page - disconnected state

### ISSUE THREAD

**Issue by 0xVenky** [levelkdev/swapr-dapp#887]

**Comment by Diogomartf** [comment]
I think this is empty state.

<img width="843" alt="image" src="https://user-images.githubusercontent.com/5664434/163889696-7b88d71f-257b-4e57-b54c-8734793a380b.png">

**Comment by MilanVojnovic95** [comment]
@0xVenky @Diogomartf 
Right now when wallet is not connected it shows all Liquidity pairs on Liquidity page on any network (except polygon)
Should we close this issue?

**Comment by 0xVenky** [comment]
Yea, seems to be redundant and not required. Even if we launch our core contracts on other networks, we would have created a few pools / pairs I think :) @zamli check once and lets close this issue.

**Comment by 0xVenky** [comment]
Hey @Diogomartf @MilanVojnovic95  This issue was about how the below view will be displayed on a disconnected wallet. As you might see, there are some sections that will become irrelevant when in disconnected state. So, that might warrant some work to be done. :) 

![image](https://user-images.githubusercontent.com/55109759/171849645-298d89a2-11de-41fa-8147-7370528ffb7e.png)

**Comment by Diogomartf** [comment]
We might not show "your liquidity" section, is that it?
