### ISSUE TITLE
Add a loading indicator to swap button while computing Eco Router routes

### ISSUE THREAD

**Issue by adamazad** [levelkdev/swapr-dapp#894]
**Description**

While the Eco Router is computing the routes, the swap button label is "Price Impact too high"

#### Definition of done
- [ ] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**How to Reproduce**
1. Go to Swap page
2. Choose the sell token, and then the buy token.
3. Input a sell amount
4. The swap button label is "Price Impact too high"

**Expected behavior**

Should show a loading indicator

**Screenshots**

<img width="712" alt="image" src="https://user-images.githubusercontent.com/1926216/163513069-61ba324b-108e-4b6d-a250-b74f098dab30.png">

**Additional context**

It might help if the connection is manually throttled from Developer Tools.

**Comment by jorgedclopes** [comment]
This processing is done in sync.
We'll need to change to async processing while managing that button label message.
Meaning that it is not simple to do processing in between. It's actually more than just a couple of hours of work.
