### ISSUE TITLE
Opening a rewards campaign for pair that have no liquidity causes app crash

### ISSUE THREAD

**Issue by niemam29** [levelkdev/swapr-dapp#919]
**Description**
On Rinkeby network there is a pair without any liquidity (at the moment of creating this task) - DAI/USDT. Opening a rewards campaign causes division by zero exception.

#### Definition of done
- [X] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**How to Reproduce**
1. Go to Rewards
2. Open rewards campaign for DAI/USDT or create one for pair without any liquidity

**Screenshots**
![cach2.png](https://images.zenhubusercontent.com/621e34c8aeddc379d59ee4d5/7e92862f-1f6a-4534-b7cb-a4ba1e4a7816)![cache2.png](https://images.zenhubusercontent.com/621e34c8aeddc379d59ee4d5/a5697849-f727-44cf-9b3d-84aeb94ac9b0)

**Comment by wixzi** [comment]
@niemam29 Is this bug still relevant. If it is can you share the full link with token address?

**Comment by niemam29** [comment]
@wixzi Propably fix from #964 will also help in this case, let's wait untill it's merged and then im gonna check it

**Comment by niemam29** [comment]
Fixed by #964
