### ISSUE TITLE
Fix Trust Wallet asset URLs on Gnosis Chain and Arbitrum

### ISSUE THREAD

**Issue by adamazad** [levelkdev/swapr-dapp#928]
We have issues with the Trust Wallet on Gnosis Chain. I remember the URL being hardcoded. 

<img width="904" alt="image" src="https://user-images.githubusercontent.com/1926216/165716993-21ff9682-f8b9-4b5a-a3ea-e6bb8b700aee.png">

_Originally posted by @adamazad in https://github.com/levelkdev/swapr-dapp/pull/925#pullrequestreview-956096680_

**Comment by denciu** [comment]
Incoming fix in https://github.com/levelkdev/swapr-dapp/pull/825

**Comment by denciu** [comment]
Closed by #825
