### ISSUE TITLE
Arbitrum One network doesn't work when connecting by Wallet Connect

### ISSUE THREAD

**Issue by niemam29** [levelkdev/swapr-dapp#940]
**Description**
When user tries to connect arbitrum wallet through wallet connect unsupported network error is displayed

#### Definition of done
- [x] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**How to Reproduce**
1. Click on connect wallet
2. Click on Wallet Connect
3. Scan QR code with your wallet (i was using Trust Wallet)
4. Connect with arbitrum network

**Screenshots**
![at.png](https://images.zenhubusercontent.com/621e34c8aeddc379d59ee4d5/f3aa499b-a4ae-4859-8dc0-9d1476346c67)

**Comment by kingalg** [comment]
I tested it further (as Kacper asked if I experience the same problems) and I confirm this issue.
Not all wallets support Arbitrum so it's not so easy or obvious to check, but Tokenary (which is one of the wallets that our users can choose from WalletConnect menu) supports it. And even after trying to connect to Arbitrum through choosing this network directly in Tokenarny we display "Unsupported Network" in Swapr.

![Screenshot 2022-05-02 at 12.34.35.png](https://images.zenhubusercontent.com/61b8ae8c4021b5ba7f93dbf2/8d995f41-8399-4f13-8bab-25aafc34036f)
![Screenshot 2022-05-02 at 12.34.09.png](https://images.zenhubusercontent.com/61b8ae8c4021b5ba7f93dbf2/c5e3e13b-7a95-43d6-a0e9-0cb321c2fdd3)

**Comment by MilanVojnovic95** [comment]
Retested on *develop* branch and this bug is still present.
