### ISSUE TITLE
Connect wallet: broken images

### ISSUE THREAD

**Issue by MilanVojnovic95** [levelkdev/swapr-dapp#949]
**Description**
Bug found with Polygon supprot PR.
The point is that the icons on the connect wallet are broken

**How to Reproduce**
1. Click on connect wallet and you will see broken images
2. Click on WalletConnect and you will also se broken image ( logo )
3. Click on Coinbase  and you will also se broken image ( logo )
4. When wallet is connected click on change wallet and you will see broken images

**Screenshots**
![image](https://user-images.githubusercontent.com/57331244/166904863-31538287-cb42-4f51-8dbf-d3f23732b481.png)
![image](https://user-images.githubusercontent.com/57331244/166905152-f9a9e76c-d178-405d-a8df-ef45dd38bcfe.png)

![image](https://user-images.githubusercontent.com/57331244/166904816-85fdbb1d-b74d-4e83-b741-15f32d4d972a.png)
![image](https://user-images.githubusercontent.com/57331244/166905085-004b2cbb-4b27-456f-8878-fd2266b74aeb.png)

**Comment by 0xVenky** [comment]
Is this still a problem? 🤔  Seems like I cant reproduce this now

**Comment by MilanVojnovic95** [comment]
@0xVenky Tested and it looks like this bug has been fixed. So I'm going to close this issue.
