### ISSUE TITLE
 Polygon network is not clickable on Bridge

### ISSUE THREAD

**Issue by MilanVojnovic95** [levelkdev/swapr-dapp#950]
**Description**
On bridge the polygon network is not clickable (that may be on purpose, not sure) and the gnosis chain is in the coming soon section.

**Screenshots**
![image](https://user-images.githubusercontent.com/57331244/166902221-8dde6987-0e92-4c5f-a663-e211332db381.png)

https://user-images.githubusercontent.com/57331244/166872309-397806da-57a1-4af6-9915-b54b3cfdc0f9.mp4

**Comment by 0xVenky** [comment]
@mix1o @MilanVojnovic95 this would be fixed in the new develop right? If yes, can you close this Milan? :)

**Comment by MilanVojnovic95** [comment]
@venky Polygon not being clickable on the Bridge page should be expected behavior because EcoBridge does not support Polygon at the moment.
And the thing with the gnosis chain is in the 'coming soon' state has already been fixed.
So I'm going to close this issue 👍
