### ISSUE TITLE
Token search

### ISSUE THREAD

**Issue by MilanVojnovic95** [levelkdev/swapr-dapp#951]
**Description**
There is a bug in token search:
If you type "MA" in search "MATIC" appears (and it's correct behaviour)
But if you try search from "the middle" for example typing "TIC" MATIC will not appear (but wrapped MATIC will...)

**How to Reproduce**
1. Go to Swap page
2. Click on "Select token" on Swap box
3. Then type "MATIC" in a search bar
4. Then type "TIC"  in a search bar

**Screenshots**
![image](https://user-images.githubusercontent.com/57331244/166903930-7f3630a0-8479-4404-8200-af3de95067b3.png)
![image](https://user-images.githubusercontent.com/57331244/166904025-bd346384-94e8-48ec-96aa-d3cfa63d1126.png)

**Comment by kingalg** [comment]
We already had very similar issue resolved in the past, so maybe this will be helpful: https://app.zenhub.com/workspaces/swapr-611e5f16daa13f001932934e/issues/levelkdev/swapr-dapp/528
