### ISSUE TITLE
Swap page is not opened by default

### ISSUE THREAD

**Issue by niemam29** [levelkdev/swapr-dapp#953]
**Description**
Swap page is not opened by default

#### Definition of done
- [X] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**How to Reproduce**
1. Open swapr default page

**Expected behavior**
Landing page is opened along with swap page

**Screenshots**
![cach2.png](https://images.zenhubusercontent.com/621e34c8aeddc379d59ee4d5/d6a81491-b80d-4341-94e0-41850892ce91)

**Comment by 0xVenky** [comment]
This seems to be fixed in the latest build from #910 I have tested it and looks fine, can you also take a look once and close this if you feel its ok? @niemam29
