### ISSUE TITLE
Enable Swapr dapp support for Optimism

### ISSUE THREAD

**Issue by 0xVenky** [levelkdev/swapr-dapp#955]
Adding Optimism to Swapr includes:

SDK:

 add basic config (chainId, ETH native currency, core tokens on Optimism like WETH, USDC, USDT, etc.)
 investigate which DEXes can be ecoRouted
FE:

 enable adding/switching network to Optimism
 disable Swapr specific features when connected to Optimism (disable Liquidity, Rewards)
Bridge:

 enable Optimism support on Socket
 add bridgable tokens for Optimism

**Comment by jorgedclopes** [comment]
SDK fetches addresses from [dxswap-core](https://github.com/levelkdev/dxswap-core/blob/master/.contracts.json).

After a quick search I failed to identify the appropriate addresses for the Optimism (check link). I'll need some help on this part.
Optimism has chainIds of 10 for their mainnet, 69 for Kovan testnet and 300 for Optimism on Gnosis. A quick search [here](https://chainlist.org/) will confirm this info.

**Comment by jorgedclopes** [comment]
optimism on dexscreen shows only 2 dexes: Uniswap and Zipswap
Zipswap is very small, leaving only Uniswap
Uniswap on that chain is using V3, something we aren't compatible yet... (this is the same reason we don't have Uniswap on Polygon yet)

Until we have support for Uniswap V3 this limitation will remain.

**Comment by jorgedclopes** [comment]
Just to give an update here. The implementation is mostly done.
The only thing outstanding is the bridge token pairs. I managed to get something working but the proper solution might take a bit of time to implement.
