### ISSUE TITLE
Add Uniswap V3 Support

### ISSUE THREAD

**Issue by jorgedclopes** [levelkdev/swapr-dapp#969]
Adding Uniswap V3 to Swapr includes:

SDK:

- Add basic config Adding Polygon to Swapr includes:
    - add basic config
    - enable Uniswap V3 on Optimism, among other dexes
    - create UniswapV3RoutablePlatforms??

FE:

- Bridge:
    - Enable UniswapV3 support on Socket (if applicable)
    - Add bridgable tokens for UniswapV3 (to check; possibly already compatible with V3)
    - enable Sushiswap on Polygon
    - add Quickswap to UniswapV2RoutablePlatforms
    - enable adding/switching network to Polygon
    - disable Swapr specific features when connected to Polygon (disable Liquidity, Rewards)
    - enable Polygon support on Socket
    - add bridgable tokens for Polygon

Due to upcoming major changes in SDK, #616 is a good reference to look into as a base branch.

**Comment by sacshin** [comment]
https://uniswap.org/blog/auto-router-v2
The new Uniswap autorouter supports Arbitrum and Optimism. https://docs.uniswap.org/sdk/guides/auto-router
It also splits trades across both Uni v2 and Uni v3 liquidity pools.
