### ISSUE TITLE
Swap error message does not go away after rejecting the transaction from signer

### ISSUE THREAD

**Issue by adamazad** [levelkdev/swapr-dapp#997]
**Description**

<img width="632" alt="image" src="https://user-images.githubusercontent.com/1926216/169067433-88f90dbb-3150-44c8-a54b-5832f719051c.png">

#### Definition of done
- [x] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**How to Reproduce**
1. Go to https://swapr.site/#/swap?chainId=137
2. Select sell and buy tokens. 
3. Click on Swap
4. On Metamask reject the transaction
5. "Transaction rejected" error will be shown as in the figure above.
6. The error stays there until the page is refreshed.

**Expected behavior**

One of the following:

1- The error message should away after some time: (1-2 seconds)
2- Move the error message to a toast message to improve overall UX
3- The error message wrapper should have a dismiss button

**Comment by MilanVojnovic95** [comment]
Retested on *develop* branch and this bug is fixed.
