### ISSUE TITLE
Transaction rejected error message

### ISSUE THREAD

**Issue by MilanVojnovic95** [levelkdev/swapr-dapp#998]
**Description**
Error message is different depending on which browser is used.

#### Definition of done
- [ ] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**How to Reproduce**
1. Go to Swap page
2. Choose a tokens that you want to swap
3. Then reject transaction on purpose on Metamask
4. And you should see this error message like it is on Chrome Version 101.0.4951.64 (Official Build) (x86_64)![image](https://user-images.githubusercontent.com/57331244/169118900-7e1c0801-6ee1-49d5-b9d2-c7e3c438bc11.png)

and this is how it looks on Brave Version 1.37.111 Chromium: 100.0.4896.79 (Official Build) ![image](https://user-images.githubusercontent.com/57331244/169119085-32b2643d-9ba3-4bdd-9041-c2053c058c6c.png)

**Comment by adamazad** [comment]
Related to #997

**Comment by niemam29** [comment]
This depends not on the browser but on the expert mode toggle.
